apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: redis
    app: todoapp
  namespace: dev  
spec:
      containers:
      - image: redis
        name: redis
        ports:
        - name: redis
          containerPort: 6379
        
              
