apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: redis
    app: todoapp
  namespace: dev  
spec:
  selector:
    name: redis
  type: ClusterIP
  ports:
    - name: db
      port: 6379
      targetPort: 6379
