apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: todoapp
spec: 
  containers: 
    - image: devopsjuly22017/web
      name: myweb
      ports: 
        - containerPort: 5000
