apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: todoapp
  namespace: dev
spec:
  selector:
    name: web 
  type: NodePort
  ports:
   - name: http
     port: 5000
     targetPort: 5000
     protocol: TCP
